In [87]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [88]:
df = pd.read_csv("../data/raw/automobileEDA_dirty_training.csv")
df.head()

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [89]:
print(f"data berbentuk {df.shape[0]} baris dan {df.shape[1]} kolom")

data berbentuk 205 baris dan 30 kolom

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_date   203 non-null    str
 1   symboling          205 non-null    int64
 2   normalized-losses  205 non-null    int64
 3   make               203 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       203 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         202 non-null    float64
 22  peak-rpm           205 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              202 non-null    float64
 26  city-L/100km       205 non-null    float64
 27  horsepower-binned  204 non-null    str
 28  diesel             205 non-null    int64
 29  gas                205 non-null    int64
dtypes: float64(11), int64(8), str(11)
memory usage: 48.2 KB

In [91]:
df.describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000,205.000000,202.000000,205.000000,205.000000,205.000000,202.000000,205.000000,205.000000,205.000000
mean,0.839024,122.058537,98.784878,0.837107,0.915095,53.762927,2554.575610,126.980488,3.329020,3.258209,10.207902,103.403526,5119.515800,25.200000,30.721951,13181.668317,9.939602,0.102439,0.897561
std,1.247916,31.748344,6.018632,0.059030,0.028986,2.439080,515.016952,41.398466,0.266929,0.316354,4.064078,37.453870,476.073141,6.446917,6.836734,7924.054951,2.537799,0.303967,0.303967
min,-2.000000,65.000000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,0.000000,101.000000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7778.250000,7.833333,0.000000,1.000000
50%,1.000000,122.000000,97.000000,0.832292,0.909722,54.100000,2420.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10320.000000,9.791667,0.000000,1.000000
75%,2.000000,137.000000,102.400000,0.881788,0.923611,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16482.500000,12.368421,0.000000,1.000000
max,3.000000,256.000000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [92]:
df.isna().sum()[df.isna().sum() > 0]

transaction_date     2
make                 2
num-of-doors         2
stroke               4
horsepower           3
price                3
horsepower-binned    1
dtype: int64

In [93]:
null_info = df.isna().sum()
null_info = null_info[null_info > 0]

result = pd.DataFrame({
    "null_count": null_info,
    "dtype": df[null_info.index].dtypes
})

result

                   null_count    dtype
transaction_date            2      str
make                        2      str
num-of-doors                2      str
stroke                      4  float64
horsepower                  3  float64
price                       3  float64
horsepower-binned           1      str

In [94]:
print("baris sebelum drop transaction_date", len(df))
df = df.dropna(subset=["transaction_date"])
print("baris setelah drop transaction_date", len(df))

baris sebelum drop transaction_date 205
baris setelah drop transaction_date 203

In [95]:
df["transaction_date"].isna().sum()

np.int64(0)

In [96]:
df[["make", "num-of-doors"]] = df[["make", "num-of-doors"]].fillna("unknown")

In [97]:
df["make"].isna().sum()

np.int64(0)

In [98]:
df["num-of-doors"].isna().sum()

np.int64(0)

In [99]:
pd.crosstab(
    pd.cut(df["horsepower"], bins=10),
    df["horsepower-binned"]
)

horsepower-binned  High  Low  Medium
horsepower
(47.786, 69.4]        0   45       0
(69.4, 90.8]          0   43       0
(90.8, 112.2]         0   25      23
(112.2, 133.6]        0    0      24
(133.6, 155.0]        0    0      16
(155.0, 176.4]       14    0       0
(176.4, 197.8]        5    0       0
(197.8, 219.2]        4    0       0

In [100]:
df[["horsepower", "horsepower-binned"]] \
    .dropna() \
    .sort_values("horsepower") \
    .drop_duplicates() \
    .loc[lambda x: x["horsepower-binned"].ne(
        x["horsepower-binned"].shift()
    )]

     horsepower horsepower-binned
17         48.0               Low
76        102.0            Medium
176       156.0              High

In [101]:
df.groupby("horsepower-binned")["horsepower"].agg(
    ["min", "max"]
)

                     min    max
horsepower-binned
High               156.0  207.0
Low                 48.0  101.0
Medium             102.0  155.0

In [102]:
df["horsepower-binned"] = df["horsepower-binned"].fillna(
    pd.cut(
        df["horsepower"],
        bins=[-float("inf"), 101, 155, float("inf")],
        labels=["Low", "Medium", "High"]
    )
)

In [103]:
df["horsepower-binned"].isna().sum()

np.int64(0)

In [104]:
df["stroke"] = df["stroke"].fillna(df["stroke"].mean())

In [105]:
df["stroke"].isna().sum()

np.int64(0)

In [106]:
df["price"].skew()

np.float64(1.812875843547854)

In [107]:
df["price"] = df["price"].fillna(df["price"].median())

In [108]:
df["price"].isna().sum()

np.int64(0)

In [109]:
df["horsepower"].skew()

np.float64(1.12397242522593)

In [110]:
df["horsepower"] = df["horsepower"].fillna(
    df.groupby("horsepower-binned", observed=True)["horsepower"]
      .transform("median")
)

In [111]:
df["horsepower"].isna().sum()

np.int64(0)

In [112]:
df.isna().sum()

transaction_date     0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    0
diesel               0
gas                  0
dtype: int64

In [113]:
len(df)

203

In [114]:
df = df.drop_duplicates()

In [115]:
len(df)

199

In [116]:
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"], errors="coerce", format="mixed"
)

In [117]:
df.head(10)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,2025-02-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,2025-01-03,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2025-01-04,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
5,2025-06-01,2,122,audi,std,two,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1
6,2025-01-07,1,158,audi,std,four,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710.0,12.368421,Medium,0,1
7,2025-01-08,1,122,audi,std,four,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920.0,12.368421,Medium,0,1
8,2025-01-09,1,158,audi,turbo,four,SEDAN,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1
9,2025-10-01,2,192,bmw,std,two,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430.0,10.217391,Low,0,1

In [118]:
df["make"].value_counts()

make
toyota           33
mazda            17
nissan           17
mitsubishi       12
volkswagen       12
honda            11
subaru           11
volvo            11
peugot           10
bmw               8
dodge             8
mercedes-benz     8
plymouth          7
audi              6
saab              6
chevrolet         3
jaguar            3
porsche           3
alfa-romero       2
isuzu             2
renault           2
ALFA-ROMERO       1
dodge             1
Audi              1
mercury           1
BMW               1
unknown           1
porsche           1
Name: count, dtype: int64

In [119]:
df["make"].value_counts()

make
toyota           33
mazda            17
nissan           17
mitsubishi       12
volkswagen       12
honda            11
subaru           11
volvo            11
peugot           10
bmw               8
dodge             8
mercedes-benz     8
plymouth          7
audi              6
saab              6
chevrolet         3
jaguar            3
porsche           3
alfa-romero       2
isuzu             2
renault           2
ALFA-ROMERO       1
dodge             1
Audi              1
mercury           1
BMW               1
unknown           1
porsche           1
Name: count, dtype: int64

In [120]:
cols = ["make", "body-style", "drive-wheels", "fuel-system"]
df[cols] = df[cols].apply(lambda col: col.str.lower().str.strip())

In [121]:
df["make"].value_counts()

make
toyota           33
mazda            17
nissan           17
mitsubishi       12
volkswagen       12
honda            11
subaru           11
volvo            11
peugot           10
bmw               9
dodge             9
mercedes-benz     8
audi              7
plymouth          7
saab              6
porsche           4
alfa-romero       3
chevrolet         3
jaguar            3
isuzu             2
renault           2
mercury           1
unknown           1
Name: count, dtype: int64

In [122]:
df["num-of-doors"].value_counts()

num-of-doors
four       112
two         85
unknown      2
Name: count, dtype: int64

In [123]:
df["num-of-cylinders"].value_counts()

num-of-cylinders
four      155
six        24
five       10
two         4
eight       4
three       1
twelve      1
Name: count, dtype: int64

In [124]:
mapping = {
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
    "unknown": -1
}

cols = ["num-of-doors", "num-of-cylinders"]

df[cols] = df[cols].replace(mapping)

In [125]:
df["num-of-doors"].value_counts()

num-of-doors
4     112
2      85
-1      2
Name: count, dtype: int64

In [126]:
df["num-of-cylinders"].value_counts()

num-of-cylinders
4     155
6      24
5      10
2       4
8       4
3       1
12      1
Name: count, dtype: int64

In [127]:
df.head(20)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,2,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,2025-02-01,3,122,alfa-romero,std,2,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,2025-01-03,1,122,alfa-romero,std,2,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2025-01-04,2,164,audi,std,4,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,4,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
5,2025-06-01,2,122,audi,std,2,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250.0,12.368421,Medium,0,1
6,2025-01-07,1,158,audi,std,4,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710.0,12.368421,Medium,0,1
7,2025-01-08,1,122,audi,std,4,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920.0,12.368421,Medium,0,1
8,2025-01-09,1,158,audi,turbo,4,sedan,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1
9,2025-10-01,2,192,bmw,std,2,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430.0,10.217391,Low,0,1
10,2025-01-11,0,192,bmw,std,4,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,10320.0,10.217391,Low,0,1
11,2025-01-12,0,188,bmw,std,2,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,20970.0,11.190476,Medium,0,1
12,2025-01-13,0,188,bmw,std,4,sedan,awd,front,101.2,...,9.0,121.0,4250.0,21,28,21105.0,11.190476,Medium,0,1
13,2025-01-14,1,122,bmw,std,4,sedan,rwd,front,103.5,...,9.0,121.0,4250.0,20,25,24565.0,11.750000,Medium,0,1
14,2025-01-15,0,122,bmw,std,4,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,30760.0,14.687500,High,0,1
15,2025-01-16,0,122,bmw,std,-1,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,41315.0,14.687500,High,0,1
16,2025-01-17,0,122,bmw,std,4,sedan,rwd,front,110.0,...,8.0,182.0,5400.0,15,20,36880.0,15.666667,High,0,1
17,2025-01-18,2,121,chevrolet,std,2,hatchback,fwd,front,88.4,...,9.5,48.0,5100.0,47,53,5151.0,5.000000,Low,0,1
18,2025-01-19,1,98,chevrolet,std,2,hatchback,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6295.0,6.184211,Low,0,1
19,2025-01-20,0,81,chevrolet,std,4,sedan,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6575.0,6.184211,Low,0,1

In [128]:
df.shape

(199, 30)

In [ ]:
# df.to_csv("../data/raw/cleaned.csv")

In [130]:
scaler = MinMaxScaler()

In [ ]:
cols_to_normalize = [
    "normalized-losses",
    "wheel-base",
    "length",
    "width",
    "height",
    "curb-weight",
    "engine-size",
    "bore",
    "stroke",
    "compression-ratio",
    "horsepower",
    "peak-rpm",
    "city-mpg",
    "highway-mpg",
    "price",
    "city-L/100km"
]

In [135]:
df[cols_to_normalize] = scaler.fit_transform(df[cols_to_normalize])

In [136]:
df.head(15)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,0.298429,alfa-romero,std,2,convertible,rwd,front,0.058309,...,0.12500,0.294393,0.346939,0.222222,0.289474,0.207959,0.481481,Medium,0,1
1,2025-02-01,3,0.298429,alfa-romero,std,2,convertible,rwd,front,0.058309,...,0.12500,0.294393,0.346939,0.222222,0.289474,0.282558,0.481481,Medium,0,1
2,2025-01-03,1,0.298429,alfa-romero,std,2,hatchback,rwd,front,0.230321,...,0.12500,0.495327,0.346939,0.166667,0.263158,0.282558,0.570175,Medium,0,1
3,2025-01-04,2,0.518325,audi,std,4,sedan,fwd,front,0.384840,...,0.18750,0.252336,0.551020,0.305556,0.368421,0.219254,0.376157,Medium,0,1
4,2025-01-05,2,0.518325,audi,std,4,sedan,4wd,front,0.373178,...,0.06250,0.313084,0.551020,0.138889,0.157895,0.306142,0.621914,Medium,0,1
5,2025-06-01,2,0.298429,audi,std,2,sedan,fwd,front,0.384840,...,0.09375,0.289720,0.551020,0.166667,0.236842,0.251527,0.570175,Medium,0,1
6,2025-01-07,1,0.486911,audi,std,4,sedan,fwd,front,0.559767,...,0.09375,0.289720,0.551020,0.166667,0.236842,0.312596,0.570175,Medium,0,1
7,2025-01-08,1,0.298429,audi,std,4,wagon,fwd,front,0.559767,...,0.09375,0.289720,0.551020,0.166667,0.236842,0.342634,0.570175,Medium,0,1
8,2025-01-09,1,0.486911,audi,turbo,4,sedan,fwd,front,0.559767,...,0.08125,0.429907,0.551020,0.111111,0.105263,0.465642,0.679739,Medium,0,1
9,2025-10-01,2,0.664921,bmw,std,2,sedan,rwd,front,0.425656,...,0.11250,0.247664,0.673469,0.277778,0.342105,0.280820,0.408213,Low,0,1
10,2025-01-11,0,0.664921,bmw,std,4,sedan,rwd,front,0.425656,...,0.11250,0.247664,0.673469,0.277778,0.342105,0.129140,0.408213,Low,0,1
11,2025-01-12,0,0.643979,bmw,std,2,sedan,rwd,front,0.425656,...,0.12500,0.341121,0.040816,0.222222,0.315789,0.393526,0.481481,Medium,0,1
12,2025-01-13,0,0.643979,bmw,std,4,sedan,awd,front,0.425656,...,0.12500,0.341121,0.040816,0.222222,0.315789,0.396877,0.481481,Medium,0,1
13,2025-01-14,1,0.298429,bmw,std,4,sedan,rwd,front,0.492711,...,0.12500,0.341121,0.040816,0.194444,0.236842,0.482771,0.523611,Medium,0,1
14,2025-01-15,0,0.298429,bmw,std,4,sedan,rwd,front,0.492711,...,0.06250,0.626168,0.510204,0.083333,0.157895,0.636562,0.744792,High,0,1

In [137]:
df.to_csv("../data/raw/normalized.csv")

In [138]:
categorical_cols = [
    "make",
    "aspiration",
    "body-style",
    "drive-wheels",
    "engine-location",
    "engine-type",
    "fuel-system",
    "horsepower-binned"
]

In [139]:
df = pd.get_dummies(
    df,
    columns=categorical_cols,
    dtype=int
)

In [140]:
df.head(15)

,transaction_date,symboling,normalized-losses,num-of-doors,wheel-base,length,width,height,curb-weight,num-of-cylinders,...,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi,horsepower-binned_High,horsepower-binned_Low,horsepower-binned_Medium
0,2025-01-01,3,0.298429,2,0.058309,0.413433,0.324786,0.083333,0.411171,4,...,0,0,0,0,1,0,0,0,0,1
1,2025-02-01,3,0.298429,2,0.058309,0.413433,0.324786,0.083333,0.411171,4,...,0,0,0,0,1,0,0,0,0,1
2,2025-01-03,1,0.298429,2,0.230321,0.449254,0.444444,0.383333,0.517843,6,...,0,0,0,0,1,0,0,0,0,1
3,2025-01-04,2,0.518325,4,0.384840,0.529851,0.504274,0.541667,0.329325,4,...,0,0,0,0,1,0,0,0,0,1
4,2025-01-05,2,0.518325,4,0.373178,0.529851,0.521368,0.541667,0.518231,5,...,0,0,0,0,1,0,0,0,0,1
5,2025-06-01,2,0.298429,2,0.384840,0.540299,0.512821,0.441667,0.395268,5,...,0,0,0,0,1,0,0,0,0,1
6,2025-01-07,1,0.486911,4,0.559767,0.770149,0.948718,0.658333,0.525989,5,...,0,0,0,0,1,0,0,0,0,1
7,2025-01-08,1,0.298429,4,0.559767,0.770149,0.948718,0.658333,0.568658,5,...,0,0,0,0,1,0,0,0,0,1
8,2025-01-09,1,0.486911,4,0.559767,0.770149,0.948718,0.675000,0.619860,5,...,0,0,0,0,1,0,0,0,0,1
9,2025-10-01,2,0.664921,2,0.425656,0.532836,0.384615,0.541667,0.351823,4,...,0,0,0,0,1,0,0,0,1,0
10,2025-01-11,0,0.664921,4,0.425656,0.532836,0.384615,0.541667,0.351823,4,...,0,0,0,0,1,0,0,0,1,0
11,2025-01-12,0,0.643979,2,0.425656,0.532836,0.384615,0.541667,0.474011,6,...,0,0,0,0,1,0,0,0,0,1
12,2025-01-13,0,0.643979,4,0.425656,0.532836,0.384615,0.541667,0.495345,6,...,0,0,0,0,1,0,0,0,0,1
13,2025-01-14,1,0.298429,4,0.492711,0.714925,0.564103,0.658333,0.607836,6,...,0,0,0,0,1,0,0,0,0,1
14,2025-01-15,0,0.298429,4,0.492711,0.714925,0.564103,0.658333,0.675718,6,...,0,0,0,0,1,0,0,1,0,0

In [141]:
df.to_csv("../data/processed/automobileEDA_processed.csv")